on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: C082H8H08EA
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "Here is some text"
                accessory:
                  type: "image"
                  image_url: "${{ github.event.sender.avatar_url }}"
                  alt_text: "${{ github.event.sender.login }}"

              - type: actions
                elements:
                - type: button
                  text:
                    type: "plain_text"
                    text: "View build"
                  url: "https://google.com"
